name: Convert Excel to JSON

on:
  push:
    paths:
      - data/database.xlsx

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pandas openpyxl

      - name: Write Python script to file
        run: |
          echo "import pandas as pd" > convert.py
          echo "df = pd.read_excel('data/database.xlsx')" >> convert.py
          echo "df.to_json('data/database.json', orient='records', force_ascii=False, indent=2)" >> convert.py

      - name: Run conversion script
        run: python convert.py

      - name: Commit and push JSON
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/database.json
          git diff --quiet --cached || (git commit -m "Auto-converted Excel to JSON" && git push)
