name: Excel naar JSON converter

on:
  push:
    paths:
      - 'data/database.xlsx'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pandas openpyxl

      - name: Convert Excel to JSON
        run: |
          python -c "import pandas as pd; df = pd.read_excel('data/database.xlsx'); df.to_json('data/collection.json', orient='records', indent=2, force_ascii=False)"

      - name: Commit JSON output
        run: |
          git config user.name 'github-actions'
          git config user.email 'actions@github.com'
          git add data/collection.json
          git commit -m 'Update collection.json from Excel' || echo 'No changes to commit'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
